# Generated by Django 5.1.3 on 2026-04-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
