# Generated by Django 5.1.3 on 2026-04-11 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_delete_otp'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='signup',
            managers=[
            ],
        ),
    ]
