# Generated by Django 5.1.3 on 2026-04-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_signup_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
