# Generated by Django 5.1.3 on 2026-04-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='user_id',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
