# Generated by Django 5.1.3 on 2026-04-16 08:57

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_signup_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='user_id',
        ),
        migrations.AddField(
            model_name='signup',
            name='custom_id',
            field=models.CharField(default=chat.models.generate_user_id, max_length=10, unique=True),
        ),
    ]
