# Generated by Django 5.1.3 on 2026-04-21 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
