# Generated by Django 5.1.3 on 2026-04-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_message_sender_alter_message_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
